spring:
  application:
    name: hr-user
  #H2 (Database) configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:0}

#Eureka (Service-registry) configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


