spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://hr-user-pg12:5433/db_hr_user
    username: postgres
    password: 1234567
