spring:
  application:
    name: hr-oauth

server:
  port: ${PORT:0}

#Eureka (Service-Registry) configuration
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}}
