spring:
  application:
    name: hr-api-gateway

server:
  port: 8765 #default port for api-gateway is 8765

# Eureka (Service-registry) configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Zuul (Api-gateway) configuration

zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**
