spring:
  application:
    name: hr-payroll

#Eureka (Service-Registry) configuration
eureka:
  client:
    service-url:
      defaultZone=http: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

#Ribbon (Load Balancer) configuration
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

server:
  port: ${PORT:0}

#Hystrix (Circuit breaker) configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000