spring:
  application:
    name: hr-worker

server:
  port: ${PORT:0}

#Actuator configs (refresh configs from config-server)
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Eureka (Service-Registry) configuration
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

test:
  config: this config is changed to make a test in spring actuator (refresh configs in projects)
